---
title: "Table A2 a-c"
output:
  pdf_document: default
  html_document: default
  word_document: default
header-includes: \usepackage[labelformat=empty]{caption}
---

```{r child = file.path(here::here(),'setup.Rmd')}
```

```{r}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, results='hide', message=FALSE)
```

```{r figdmi-setupdata}
dat <- fullrespdat
dat$log.CHL.2.5.mon10to12.1[is.na(dat$log.CHL.2.5.mon10to12.1)] <- -1
dat2=gam(nspawners0~nspawners1+spawners2+
           SSTICOAD.2.10.3.yr.runsum.0+Year+
           log.CHL.2.5.mon10to12.1+
           Precip.Kerala.mon6to7.0, data=dat)$model
chlNA <- dat2$log.CHL.2.5.mon10to12.1 == -1
dat2$log.CHL.2.5.mon10to12.1[chlNA] <- NA
fit2=gam(nspawners0~s(nspawners1, sp=0.6)+s(spawners2, sp=0.6), data=dat2)
fit2=gam(nspawners0~s(nspawners1, sp=0.6), data=dat2)
dat2$resid=residuals(fit2)
dat2$resid[dat2$Year==1994]<-NA
dat2$time=1:dim(dat2)[1]
dat2$cov2=MARSS::zscore(dat2$Precip.Kerala.mon6to7.0)
dat2$cov1=MARSS::zscore(dat2$SSTICOAD.2.10.3.yr.runsum)
# dat2$cov1=residuals(lm(DMI.3.yr.runsum.0~time, data=dat2))
# dat2$cov1=MARSS::zscore(dat2$cov1)
dat2$cov0=MARSS::zscore(dat2$log.CHL.2.5.mon10to12.1)
dat2$cov0[chlNA] <- 0
```

```{r figdmi-fitmodels}
library(MARSS)
qfix=0.6
Zt = array(NA, dim=c(1,3,dim(dat2)[1]))
pol <- poly(as.vector(dat2$cov1),3)
Zt[1,1,] = pol[,1]
Zt[1,2,] = pol[,2]
Zt[1,3,] = pol[,3]
A=matrix(0)
R=matrix("r")
Q=diag(1,1) #fix so doesn't go to zero
Q=matrix("q")
Q="unconstrained"
Q=diag(0, ncol(Zt)) #best re one step ahead 
Q=diag(qfix^2, ncol(Zt))
inits.list = list(x0=matrix(c(0), nrow=ncol(Zt)))
modlist = list(Z=Zt, Q=Q, U="zero", A=A, R=R)
fit.dmi <- MARSS(dat2$resid, model=modlist, silent=TRUE, method="BFGS", inits=inits.list)

library(MARSS)
Zt = array(NA, dim=c(1,3,dim(dat2)[1]))
pol <- poly(as.vector(dat2$cov2),3)
Zt[1,1,] = pol[,1]
Zt[1,2,] = pol[,2]
Zt[1,3,] = pol[,3]
A=matrix(0)
R=matrix("r")
Q=diag(1,1) #fix so doesn't go to zero
Q=matrix("q")
Q="unconstrained"
#Q=diag(.0005, ncol(Zt)) #where out of sample forecasting is not increased
Q=diag((.5*qfix)^2, ncol(Zt))
inits.list = list(x0=matrix(c(1), nrow=ncol(Zt)))
modlist = list(Z=Zt, Q=Q, U="zero", A=A, R=R)
fit.precip <- MARSS(dat2$resid, model=modlist, silent=TRUE, method="BFGS", inits=inits.list)
```


```{r}
valrmse <- function(err, win=10){
trim=1/win
trim=0
  ii = seq(1,ncol(err)-win+1)
val=c()
for(i in ii){
  val<- rbind(val,c(sqrt(mean(err["null",i:(i+win-1)]^2, trim=trim, na.rm=TRUE)), 
                    sqrt(mean(err["dmi", i:(i+win-1)]^2, trim=trim, na.rm=TRUE))))
}
return(val)
}
valtrim <- function(err, win=10, trim=0.5){
  ii = seq(1,ncol(err)-win+1)
val=c()
for(i in ii){
  val<- rbind(val,c(mean(abs(err["null",i:(i+win-1)]), trim=trim), 
                    mean(abs(err["dmi", i:(i+win-1)]), trim=trim)))
}
return(val)
}
```

```{r figdmi-makefigure, fig.cap=paste("Figure",  ref("fig:tvdmi")), fig.height=6, fig.width=6, eval=FALSE}
trim.plot=FALSE
par(mfrow=c(2,1), mar=c(3,4,2,1))
ylims=c(min(fit.dmi$states[1,], fit.precip$states[1,]), max(fit.dmi$states[1,], fit.precip$states[1,]))
plot(dat2$Year, fit.dmi$states[1,], type="l", lwd=2, ylab="Linear effect size", xlab="", col="red", ylim=ylims)
lines(dat2$Year, fit.precip$states[1,], col="grey", lwd=2)
abline(h=0, lty=2)
legend("bottomright", bty="n", 
       legend=c("SST","Precipitation"),
       col=c("red", "grey"), lwd=c(2,2))
legend("topleft", legend="a", bty="n")

#RMSE plot
err.dmi <- (rbind(null=dat2$resid, dmi=MARSSresiduals(fit.dmi)$model.residuals[1,]))
err.precip <- (rbind(null=dat2$resid, 
               dmi=MARSSresiduals(fit.precip)$model.residuals[1,]))

win=10
ii = seq(1,ncol(err.dmi)-win+1)

#RMSE plot
val <- valrmse(err.dmi, win=win)
plot(dat2$Year[ii+win], val[,1], type="l", ylim=c(log(1.1),log(2.5)), lwd=2, ylab="10 year RMSE", xlab="End year of 10-year window")
#axis(side=2, at=log(c(1, 1.10, 1.25, 1.5, 1.75, 2, 2.5)), labels=c(0, 10, 25, 50, 75, 100, 150))
lines(dat2$Year[ii+win], val[,2], col="red", lwd=2)
val <- valrmse(err.precip, win=win)
lines(dat2$Year[ii+win], val[,2], col="grey", lwd=3)
legend("topright", bty="n", 
       legend=c("No covariates", "SST","Precipitation"),
       col=c("black", "red", "grey"), lwd=c(2,2,2))
legend("topleft", legend="b", bty="n")
title("Model fit")
```

```{r figdmi-makefigure2, fig.cap=paste("Figure",  ref("fig:tvdmi")), fig.height=4, fig.width=6}
#RMSE plot
err.dmi <- (rbind(null=dat2$resid, dmi=MARSSresiduals(fit.dmi)$model.residuals[1,]))
err.precip <- (rbind(null=dat2$resid, 
               dmi=MARSSresiduals(fit.precip)$model.residuals[1,]))

win=10
ii = seq(1,ncol(err.dmi)-win+1)

#RMSE plot
val <- valrmse(err.dmi, win=win)
plot(dat2$Year[ii+win], val[,1], type="l", ylim=c(log(1.1),log(2.5)), lwd=2, ylab="10-year RMSE", xlab="End year of 10-year window")
#axis(side=2, at=log(c(1, 1.10, 1.25, 1.5, 1.75, 2, 2.5)), labels=c(0, 10, 25, 50, 75, 100, 150))
lines(dat2$Year[ii+win], val[,2], col="red", lwd=2)
val <- valrmse(err.precip, win=win)
lines(dat2$Year[ii+win], val[,2], col="grey", lwd=3)
legend("topright", bty="n", 
       legend=c("No covariates", "SST","Precipitation"),
       col=c("black", "red", "grey"), lwd=c(2,2,2))
title("Model fit - time-varying covariate effects")
```

```{r results='show', eval=FALSE}
err.dmi <- (rbind(null=dat2$resid, dmi=MARSSkfss(fit.dmi)$Innov[1,]))
err.precip <- (rbind(null=dat2$resid,
               dmi=MARSSkfss(fit.precip)$Innov[1,]))
sqrt(mean(err.dmi[1,]^2, na.rm=TRUE))
sqrt(mean(err.dmi[2,]^2, na.rm=TRUE))
sqrt(mean(err.precip[2,]^2, na.rm=TRUE))
```