---
title: "Supplemental Information: Improving landings forecasts using environmental covariates: a case study on the Indian oil sardine (*Sardinella longiceps*)"
author: EE Holmes, S BR, K Nimit, S Maity, DM Checkley, Jr., ML Wells, VL Trainer
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
header-includes: \usepackage[labelformat=empty]{caption}
---

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

# Supplement 1: Full model tests and diagnostics

*data version SardineForecast `r packageVersion("SardineForecast")`* (accepted paper used 1.11)

```{r child = file.path(here::here(), 'Rmds','SupplementalInformation1.Rmd')}
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

# Supplement 2: Data sources and raw data

*data version SardineForecast `r packageVersion("SardineForecast")`* (accepted paper used 1.11)

```{r child = file.path(here::here(), 'Rmds','SupplementalInformation2.Rmd')}
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

# Supplement 3: Ekman Mass Transport and Pumping Calculations

```{r child = file.path(here::here(), 'Rmds','SupplementalInformation3.Rmd')}
```



