---
title: 'Appendices: Non-spawner covariate tests'
output:
  pdf_document: default
  html_document: default
  word_document: default
header-includes: \usepackage[labelformat=empty]{caption}
---

```{r child = file.path(here::here(),'setup.Rmd')}
```

```{r echo=FALSE}
#set the table pre
if(Supplement){
  pre <- "S"
  tabset <- "tabsupp:"
}else{
  pre <- "A"
  tabset <- "tabapp:"
}
```

```{r child = file.path(here::here(),'AppendixFiles','Appendix-Functions.Rmd')}
```

```{r child = file.path(here::here(),'AppendixFiles','Appendix-Variables.Rmd')}
```

```{r echo=FALSE}
addchl = TRUE
add1956 = FALSE
```

```{r nonspawncovnames, echo=FALSE}
vars <- getnonspawnercovs()
datcommon <- dat.nonspawners[, 
  c("Year", "nspawners0", "spawners1", "spawners2",
    "nspawners1", "nspawners2", vars$allcovnames)]
dat <- na.omit(datcommon)

NE=mean(abs(dat$nspawners0-dat$nspawners1))
```

```{r nonspawnertablevals}
nullmod <- "$ln(W_t) = ln(W_{t-1}) + \\epsilon_t$"
basemod <- "$ln(W_t) = \\alpha + s(ln(W_{t-1})) + s(ln(S_{t-2})) + \\epsilon_t$"
resp <- "ln(W_t)"
baseformula <- "nspawners0 ~ s(nspawners1, sp=0.6) + s(spawners2, sp=0.6)"
nullformula <- "nspawners0 ~ -1 + offset(nspawners1)"
```

```{r nonspawnertable}
seltable <- makeapptable(dat, nullmod, basemod, nullformula, baseformula, resp, vars$covnamelist, vars$covlags, include.num = TRUE, isLatex = isLatex)
```

```{r nonspawncovnames1956a, echo=FALSE, eval=add1956}
covnamelist = list(
    `Select covariates available from 1957`=c(
      "Precip.Kerala.mon6to7.", "DMI.mon9to11.")
    )
covlags = list(
  Precip.Kerala.mon6to7. = c(0),
  DMI.mon9to11. = c(1),
  tide.level.interp.mon8to8. = 1)
allcovnames <- c()
for(i in 1:length(covlags)) allcovnames <- c(allcovnames, paste0(names(covlags[i]), covlags[[i]]))

datcommon <- dat.nonspawners[, 
  c("Year", "nspawners0", "spawners1", "spawners2",
    "nspawners1", "nspawners2", allcovnames)]
datcommon <- subset(datcommon, Year < 1990)
dat <- na.omit(datcommon)
```

```{r nonspawnertable1956a, eval=add1956}
seltable = rbind(seltable, spacetmp)
tabbody <- makeapptable(dat, nullmod, basemod, nullformula, baseformula, resp, covnamelist, covlags, include.num = TRUE, isLatex = isLatex)
seltable <- rbind(seltable, tabbody)
```


```{r nonspawnchlnames, echo=FALSE, eval=addchl}
vars <- getnonspawnerchlcovs()
datcommon <- dat.chl[, 
  c("Year", "nspawners0", "spawners1", "spawners2",
    "nspawners1", "nspawners2", vars$allcovnames)]
dat <- na.omit(datcommon)
```

```{r nonspawnertablechlvals, eval=addchl}
basemod <- "$ln(W_t) = \\alpha + p(ln(W_{t-1})) + p(ln(S_{t-2})) + \\epsilon_t$"
baseformula <- "nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(spawners2, 2, raw=TRUE)"
m3form <- "poly(cov, 2, raw=TRUE)"
```

```{r nonspawnerchltable, eval=addchl}
seltable = rbind(seltable, spacetmp)
chlbody <- makeapptable(dat, nullmod, basemod, nullformula, baseformula, resp, vars$covnamelist, vars$covlags, m3form=m3form, include.num = TRUE, isLatex = isLatex)
seltable <- rbind(seltable, chlbody)
```

```{r print-apptable2, echo=FALSE}
seltable = seltable[,c("Model", "Residual.df", "Adj.R2", "RMSE", "AIC", "LOOCV", "LOOMd")]
colnames(seltable) <- c("Model", "Resid. df", "Adj. R2", "RMSE", "AICc", "LOOCV RMSE", "LOOCV MdAE")
if(isLatex) colnames(seltable)=c("Model", "\\shortstack{Resid.\\\\df}", "\\shortstack{Adj.\\\\$R^2$}", "RMSE", "AICc", "\\shortstack{LOOCV\\\\RMSE}", "\\shortstack{LOOCV\\\\MdAE}")

thecap=paste("Covariate tests for the Oct-Mar catch ($W_t$) using the more complex model. M is the base model with prior season Oct-Mar catch ($W_{t-1}$) and Jul-Sep catch two seasons prior ($S_{t-2}$) as the covariates. To the base model, the  environmental covariates are added. Nearshore is 0-80km and regional is 0-160km. The SST data are from AVHRR. The models are nested sets, e.g. 1, 2a, 3a and 1, 2b, 3b.")
fullcap=paste("Table ", ref(paste0(tabset,"nonspawnercovariate-models"), pre=pre), ". ", thecap, sep="")
notes <- "LOOCV = Leave one out cross-validation. RMSE = root mean square error. MdAE = median absolute error. AICc = Akaike Information Criterion corrected for small sample size. $\\dagger$ and $\\dagger\\dagger$ = AICc greater than 2 and greater than 5 below model M (base catch model).  $\\ddagger$, $\\ddagger\\ddagger$, and ${\\ddagger}{\\ddagger}{\\ddagger}$  = LOOCV RMSE 5\\%, 10\\% and 20\\% below model M, respectively. *t* indicates current year and *t-1* is the prior year. *W~t~* spans two calendar years (Oct-Mar); *t* is the year in Oct. Thus if *t*=2014, *W~t~* is Oct 2014 to Mar 2015 and *W~t-1~* is Oct 2013 to Mar 2014. For covariates that are multiyear, such as the multiyear average SST, *t* is the calendar year at the end of the multiyear span; thus the 2.5 year average SST for 2014 is Jan 2012 to Jun 2014."
if(isLatex){
  latexkable(seltable, fullcap)
}else{
# kable(seltable, align=paste0("l", paste0(rep("c",dim(seltable)[2]-1),collapse="")), caption=fullcap, escape=FALSE)
library(kableExtra)
seltable %>%
  kbl(caption = fullcap, escape=FALSE, align=paste0("l", paste0(rep("c",dim(seltable)[2]-1),collapse=""))) %>%
  kable_classic(full_width = FALSE) %>%
  footnote(general = notes, general_title = "Notes: ", footnote_as_chunk = TRUE)
}
```

```{r eval=isLatex, results='asis'}
cat("Notes: LOOCV = Leave one out cross-validation. RMSE = root mean square error. MdAE = median absolute error. AICc = Akaike Information Criterion corrected for small sample size. $\\dagger$ and $\\dagger\\dagger$ = AICc greater than 2 and greater than 5 below model M (base catch model).  $\\ddagger$, $\\ddagger\\ddagger$, and ${\\ddagger}{\\ddagger}{\\ddagger}$  = LOOCV RMSE 5\\%, 10\\% and 20\\% below model M, respectively. $t$ indicates current year and $t-1$ is the prior year. $W_t$ spans two calendar years (Oct-Mar); $t$ is the year in Oct. Thus if $t=2014$, $W_t$ is Oct 2014 to Mar 2015 and $W_{t-1}$ is Oct 2013 to Mar 2014. For covariates that are multiyear, such as the multiyear average SST, $t$ is the calendar year at the end of the multiyear span; thus the 2.5 year average SST for 2014 is Jan 2012 to Jun 2014.")
```