---
title: "Table A2 a-c"
output:
  pdf_document: default
  html_document: default
  word_document: default
header-includes: \usepackage[labelformat=empty]{caption}
---

```{r child = file.path(here::here(),'setup.Rmd')}
```

```{r}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r figdmi-setupdata, results='hide'}
dat <- fullrespdat
dat2=gam(nspawners0~nspawners1+spawners2+
           SSTICOAD.2.10.3.yr.runsum.0+Year+
           AMO.mon7to6.0 +
           Precip.Kerala.mon6to7.0, data=dat)$model
fit2=gam(nspawners0~s(nspawners1, sp=0.6)+s(spawners2, sp=0.6), data=dat2)
fit2=gam(nspawners0~s(nspawners1, sp=0.6), data=dat2)
dat2$resid=residuals(fit2)
dat2$resid[dat2$Year==1994]<-NA
dat2$time=1:dim(dat2)[1]
dat2$cov3=MARSS::zscore(dat2$AMO.mon7to6.0)
dat2$cov2=MARSS::zscore(dat2$Precip.Kerala.mon6to7.0)
dat2$cov1=MARSS::zscore(dat2$SSTICOAD.2.10.3.yr.runsum)
```

```{r figdmi-fitmodels, results='hide'}
library(MARSS)
qfix=0.6
Zt = array(NA, dim=c(1,3,dim(dat2)[1]))
pol <- poly(as.vector(dat2$cov1),3)
Zt[1,1,] = pol[,1]
Zt[1,2,] = pol[,2]
Zt[1,3,] = pol[,3]
A=matrix(0)
R=matrix("r")
Q=diag(1,1) #fix so doesn't go to zero
Q=matrix("q")
Q="unconstrained"
Q=diag(0, ncol(Zt)) #best re one step ahead 
Q=diag(qfix^2, ncol(Zt))
inits.list = list(x0=matrix(c(0), nrow=ncol(Zt)))
modlist = list(Z=Zt, Q=Q, U="zero", A=A, R=R)
fit.dmi <- MARSS(dat2$resid, model=modlist, silent=TRUE, method="BFGS", inits=inits.list)

library(MARSS)
Zt = array(NA, dim=c(1,3,dim(dat2)[1]))
pol <- poly(as.vector(dat2$cov2),3)
Zt[1,1,] = pol[,1]
Zt[1,2,] = pol[,2]
Zt[1,3,] = pol[,3]
A=matrix(0)
R=matrix("r")
Q=diag(1,1) #fix so doesn't go to zero
Q=matrix("q")
Q="unconstrained"
#Q=diag(.0005, ncol(Zt)) #where out of sample forecasting is not increased
Q=diag((.5*qfix)^2, ncol(Zt))
inits.list = list(x0=matrix(c(1), nrow=ncol(Zt)))
modlist = list(Z=Zt, Q=Q, U="zero", A=A, R=R)
fit.precip <- MARSS(dat2$resid, model=modlist, silent=TRUE, method="BFGS", inits=inits.list)

library(MARSS)
qfix=0.6
Zt = array(NA, dim=c(1,3,dim(dat2)[1]))
pol <- poly(as.vector(dat2$cov3),3)
Zt[1,1,] = pol[,1]
Zt[1,2,] = pol[,2]
Zt[1,3,] = pol[,3]
A=matrix(0)
R=matrix("r")
Q=diag(1,1) #fix so doesn't go to zero
Q=matrix("q")
Q="unconstrained"
Q=diag(0, ncol(Zt)) #best re one step ahead 
Q=diag(qfix^2, ncol(Zt))
inits.list = list(x0=matrix(c(0), nrow=ncol(Zt)))
modlist = list(Z=Zt, Q=Q, U="zero", A=A, R=R)
fit.amo <- MARSS(dat2$resid, model=modlist, silent=TRUE, method="BFGS", inits=inits.list)
```


```{r, results='hide'}
valrmse <- function(err, win=10){
trim=1/win
trim=0
  ii = seq(1,ncol(err)-win+1)
val=c()
for(i in ii){
  val<- rbind(val,c(sqrt(mean(err["null",i:(i+win-1)]^2, trim=trim, na.rm=TRUE)), 
                    sqrt(mean(err["dmi", i:(i+win-1)]^2, trim=trim, na.rm=TRUE))))
}
return(val)
}
valtrim <- function(err, win=10, trim=0.5){
  ii = seq(1,ncol(err)-win+1)
val=c()
for(i in ii){
  val<- rbind(val,c(mean(abs(err["null",i:(i+win-1)]), trim=trim), 
                    mean(abs(err["dmi", i:(i+win-1)]), trim=trim)))
}
return(val)
}
```

```{r echo=FALSE}
thecap <- "Model fit over 10-year windows for dynamic linear models of October-March catch 1960-2015 using the 2.5-year average SST from the ICOADS data set, June-July precipitation over land (from land gauges), and Atlantic Multidecadal Oscillation index as covariates. These models allowed the covariate model to evolve over time. The models were fit to the residuals of the simpler base model (with only prior October-March catch as a covariate) with the 1994 residual was removed. The covariates were z-scored (mean removed and standardized to variance of 1) and included as a third-order polynomial to allow a non-linear effect. The plot shows the RMSE of the model residuals computed on a 10-year sliding window."
fullcap <- paste0("Figure ",  ref("fig:tvdmi"), ". ", thecap)
```

```{r figdmi-makefigure2, fig.cap=fullcap, fig.align='center', fig.height=6, fig.width=8, results='hide'}
#RMSE plot
err.dmi <- (rbind(null=dat2$resid, dmi=MARSSresiduals(fit.dmi)$model.residuals[1,]))
err.precip <- (rbind(null=dat2$resid, 
               dmi=MARSSresiduals(fit.precip)$model.residuals[1,]))
err.amo <- (rbind(null=dat2$resid, 
               dmi=MARSSresiduals(fit.amo)$model.residuals[1,]))

win=10
ii = seq(1,ncol(err.dmi)-win+1)

#RMSE plot
val <- valrmse(err.dmi, win=win)
plot(dat2$Year[ii+win], val[,1], type="l", ylim=c(log(1.1),log(2.5)), lwd=2, ylab="10-year RMSE", xlab="End year of 10-year window")
lines(dat2$Year[ii+win], val[,2], col="red", lwd=2)
val <- valrmse(err.precip, win=win)
lines(dat2$Year[ii+win], val[,2], col="grey", lwd=3)
val <- valrmse(err.amo, win=win)
lines(dat2$Year[ii+win], val[,2], col="blue", lwd=2)
val <- valrmse(err.dmi, win=win)
lines(dat2$Year[ii+win], val[,2], col="red", lwd=2)
legend("topright", bty="n", 
       legend=c("Base model (M)", "M + SST","M + Precip", "M + AMO"),
       col=c("black", "red", "grey", "blue"), lwd=c(2,2,2,2))
title("Model fit - time-varying covariate effects")
```
