---
title: 'Appendix C: Spawner and Non-Spawner Chlorophyll Analysis'
output:
  pdf_document: default
  html_document: default
  word_document: default
---

<!-- 
header-includes: \usepackage[labelformat=empty]{caption}

Generic setup code common across all Rmds; run code in setup.Rmd if not knitting.
--> 
```{r child = file.path(here::here(),'setup.Rmd')}
```

```{r echo=FALSE}
#set the table pre
if(Supplement){
  pre <- "S"
  tabset <- "tabsupp:"
}else{
  pre <- "C"
  tabset <- "tabappC:"
}
```

```{r table-appC-dat, echo=FALSE}
#dat.spawners defined in setup.Rmd
dat=dat.chl
Yr1 = min(dat$Year)
Yr2 = max(dat$Year)
NE=mean(abs(dat$spawners0-dat$spawners1))
```

```{r table-appC-spawner, echo=FALSE}
#set up table
seltable = data.frame(
  Model=paste("base model (M) ", Yr1,"-", Yr2, " data", sep=""), 
  Residual.df="", 
  MASE="",
  Adj.R2="", 
  F="", 
  p.value="", 
  AIC="", stringsAsFactors=FALSE)

m1 = gam(spawners0 ~ poly(nspawners1, 2, raw=TRUE), data=dat.chl)
m2 = gam(spawners0 ~ poly(nspawners1, 3, raw=TRUE), data=dat.chl)
a=anova(m1,m2, test="F")

#model 1
i=1; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="1. $ln(S_t) = \\alpha + p(ln(W_{t-1})) + \\epsilon_t$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F="", p.value="", 
  AIC=round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

## Add space
tmp1 = data.frame(Model="\\kern 1em", Residual.df="\\kern 1em", MASE="\\kern 1em", Adj.R2="\\kern 1em", F="\\kern 1em", p.value="\\kern 1em", AIC="")
seltable=rbind(seltable,tmp1)

for(covname in c("log.CHL.2.5.mon7to9.")){
#set up table
  if(covname=="log.CHL.4.mon1to3.")   covtit = "$V_t$ = Jan-Mar Chlorophyll"
  if(covname=="log.CHL.4.mon7to9.")   covtit = "$V_t$ = Jul-Sep Chlorophyll"
  if(covname=="log.CHL.4.mon10to12.") covtit = "$V_t$ = Oct-Dec Chlorophyll"
  if(covname=="log.CHL.2.5.mon1to3.")   covtit = "$V_t$ = Jan-Mar ns-CHL"
  if(covname=="log.CHL.2.5.mon7to9.")   covtit = "$V_t$ = Jul-Sep ns-CHL"
  if(covname=="log.CHL.2.5.mon10to12.") covtit = "$V_t$ = Oct-Dec ns-CHL"

#var header
seltable = rbind(seltable, data.frame(Model=covtit, Residual.df="", MASE="", Adj.R2="", F="", p.value="", AIC="", stringsAsFactors=FALSE))

#set up the cov0 and cov1 variables
dat$cov0=dat[[paste(covname, "0", sep="")]]
dat$cov1=dat[[paste(covname, "1", sep="")]]
m1 = gam(spawners0 ~ poly(nspawners1, 2, raw=TRUE), data=dat)
m2 = gam(spawners0 ~ poly(nspawners1, 2, raw=TRUE) + cov0, data=dat)
m3 = gam(spawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(cov0, 2, raw=TRUE), data=dat)
m4 = gam(spawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(cov0, 2, raw=TRUE) + cov1, data=dat)
m5 = gam(spawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(cov0, 2, raw=TRUE) + poly(cov1, 2, raw=TRUE), data=dat)
a=anova(m1,m2,m3,m4,m5, test="F")

#model 2
i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="2. $ln(S_t) = M + \\beta V_t$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#model 3
i=3; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="3. $ln(S_t) = M + p(V_t)$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#model 4
i=4; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="4. $ln(S_t) = M + p(V_t) + \\beta V_{t-1}$", 
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#model 5
i=5; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="5. $ln(S_t) = M + p(V_t) + p(V_{t-1})$", 
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

## Add space
tmp1 = data.frame(Model="\\kern 1em", Residual.df="\\kern 1em", MASE="\\kern 1em", Adj.R2="\\kern 1em", F="\\kern 1em", p.value="\\kern 1em", AIC="")
seltable=rbind(seltable,tmp1)
}

for(covname in c("log.CHL.2.5.mon10to12.", "log.CHL.2.5.mon1to3.")){
#set up table
  if(covname=="log.CHL.2.10.mon1to3.")   covtit = "$V_t$ = Jan-Mar r-CHL"
  if(covname=="log.CHL.2.10.mon7to9.")   covtit = "$V_t$ = Jul-Sep r-CHL"
  if(covname=="log.CHL.2.10.mon10to12.") covtit = "$V_t$ = Oct-Dec r-CHL"
  if(covname=="log.CHL.2.5.mon1to3.")   covtit = "$V_t$ = Jan-Mar ns-CHL"
  if(covname=="log.CHL.2.5.mon7to9.")   covtit = "$V_t$ = Jul-Sep ns-CHL"
  if(covname=="log.CHL.2.5.mon10to12.") covtit = "$V_t$ = Oct-Dec ns-CHL"

#var header
seltable = rbind(seltable, data.frame(Model=covtit, Residual.df="", MASE="", Adj.R2="", F="", p.value="", AIC="", stringsAsFactors=FALSE))

#set up the cov0 and cov1 variables
dat$cov0=dat[[paste(covname, "0", sep="")]]
dat$cov1=dat[[paste(covname, "1", sep="")]]
m1 = gam(spawners0 ~ poly(nspawners1, 2, raw=TRUE), data=dat)
m2 = gam(spawners0 ~ poly(nspawners1, 2, raw=TRUE) + cov1, data=dat)
m3 = gam(spawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(cov1, 2, raw=TRUE), data=dat)
a=anova(m1,m2,m3, test="F")

#model 2
i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="2. $ln(S_t) = M + \\beta V_{t-1}$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#model 3
i=3; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="3. $ln(S_t) = M + p(V_{t-1})$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

## Add space
tmp1 = data.frame(Model="\\kern 1em", Residual.df="\\kern 1em", MASE="\\kern 1em", Adj.R2="\\kern 1em", F="\\kern 1em", p.value="\\kern 1em", AIC="")
seltable=rbind(seltable,tmp1)
}
# Remove space at top and bottom
seltable=seltable[1:(dim(seltable)[1]-1),]
```

```{r print-tableAppC-spawners, echo=FALSE}
colnames(seltable)=c("Model", "Residual df", "MASE", "Adj.R2", "F", "p value", "AIC")
if(isLatex) colnames(seltable)=c("Model", "\\shortstack{Residual\\\\df}", "MASE", "\\shortstack{Adj.\\\\R2}", "F", "\\shortstack{p\\\\value}", "AIC")

thecap=paste("Model selection tests of nearshore (0-80km boxes 2 to 5) chlorophyll-a (ns-CHL) as an explanatory variable for the Jul-Sep catch ($S_t$) using", Yr1, "to", Yr2,  "data.  The data range is determined by the years for which CHL was available. Only CHL in Oct-Dec and Jan-Mar in the current season (which runs Jul-Jun) is not used since these months are after the Jul-Sep catch being modeled.  Non-linearity is modeled as a 2nd-order polynomial due to data constraints and appears as $p()$ in the model equations.  The Jul-Sep catch is modeled as a function of Oct-Mar catch in the prior year only, without Jul-Sep catch 2-years prior as in the other covariate analyses.  This is done due to data constraints. The models are nested; the Roman numeral indicates the level of nestedness. Models at levels II and higher are shown with the component that is added to the base level model (M) at top.")
fullcap=paste("Table ", ref(paste0(tabset,"spawner-model"), pre=pre), ". ", thecap, sep="")
kable(seltable, align="lcccccc", caption=fullcap, row.names=FALSE, escape=FALSE)
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

```{r table-appC-nonspawner, echo=FALSE}
#set up table
seltable = data.frame(
  Model=paste("base model (M) ", Yr1,"-", Yr2, " data", sep=""), 
  Residual.df="", 
  MASE="",
  Adj.R2="", 
  F="", 
  p.value="", 
  AIC="", stringsAsFactors=FALSE)

m1 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE), data=dat.chl)
m2 = gam(nspawners0 ~ poly(nspawners1, 3, raw=TRUE), data=dat.chl)
a=anova(m1,m2, test="F")
NE=mean(abs(dat$nspawners0-dat$nspawners1))

#model 1
i=1; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="1-M. $ln(W_t) = \\alpha + p(ln(W_{t-1})) + \\epsilon_t$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F="", p.value="", 
  AIC=round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

## Add space
tmp1 = data.frame(Model="\\kern 1em", Residual.df="\\kern 1em", MASE="\\kern 1em", Adj.R2="\\kern 1em", F="\\kern 1em", p.value="\\kern 1em", AIC="")
seltable=rbind(seltable,tmp1)

for(covname in c("log.CHL.2.5.mon7to9.", "log.CHL.2.5.mon10to12.", "log.CHL.2.5.mon1to3.")){
#set up table
  if(covname=="log.CHL.4.mon1to3.")   covtit = "$V_t$ = Jan-Mar CHL"
  if(covname=="log.CHL.4.mon7to9.")   covtit = "$V_t$ = Jul-Sep CHL"
  if(covname=="log.CHL.4.mon10to12.") covtit = "$V_t$ = Oct-Dec CHL"
  if(covname=="log.CHL.2.5.mon1to3.")   covtit = "$V_t$ = Jan-Mar ns-CHL"
  if(covname=="log.CHL.2.5.mon7to9.")   covtit = "$V_t$ = Jul-Sep ns-CHL"
  if(covname=="log.CHL.2.5.mon10to12.") covtit = "$V_t$ = Oct-Dec ns-CHL"


#set up the cov0 and cov1 variables
dat$cov0=dat[[paste(covname, "0", sep="")]]
dat$cov1=dat[[paste(covname, "1", sep="")]]
m1 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE), data=dat)
m2 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + cov0, data=dat)
m3 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(cov0, 2, raw=TRUE), data=dat)
m4 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(cov0, 2, raw=TRUE) + cov1, data=dat)
m5 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(cov0, 2, raw=TRUE) + poly(cov1, 2, raw=TRUE), data=dat)
a=anova(m1,m2,m3,m4,m5, test="F")

#var header
seltable = rbind(seltable, data.frame(Model=covtit, Residual.df="", MASE="", Adj.R2="", F="", p.value="", AIC="", stringsAsFactors=FALSE))

#model 2
i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="2. $ln(W_t) = M + \\beta V_t$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#model 3
i=3; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="3. $ln(W_t) = M + p(V_t)$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

if(covname=="log.CHL.4.mon10to12."){
#model 4
i=4; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="4. $ln(W_t) = M + p(V_t) + \\beta V_{t-1}$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#model 5
i=5; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="5. $ln(W_t) = M + p(V_t) + p(V_{t-1})$", 
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)
}

m1 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE), data=dat)
m2 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + cov1, data=dat)
m3 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + s(cov1, sp=0.6), data=dat)
a=anova(m1,m2,m3, test="F")

#model 2
i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="2. $ln(W_t) = M + \\beta V_{t-1}$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#model 3
i=3; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="3. $ln(W_t) = M + p(V_{t-1})$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

## Add space
tmp1 = data.frame(Model="\\kern 1em", Residual.df="\\kern 1em", MASE="\\kern 1em", Adj.R2="\\kern 1em", F="\\kern 1em", p.value="\\kern 1em", AIC="")
seltable=rbind(seltable,tmp1)
}

# Remove space at top and bottom
seltable=seltable[1:(dim(seltable)[1]-1),]
```

```{r print-tableAppC-nonspawners, echo=FALSE}
colnames(seltable)=c("Model", "Residual df", "MASE", "Adj.R2", "F", "p value", "AIC")
if(isLatex) colnames(seltable)=c("Model", "\\shortstack{Residual\\\\df}", "MASE", "\\shortstack{Adj.\\\\R2}", "F", "\\shortstack{p\\\\value}", "AIC")

thecap=paste("Model selection tests of nearshore (0-80km boxes 2 to 5) chlorophyll-a (ns-CHL) as an explanatory variable for Oct-Mar catch ($W_t$) using", Yr1, "to", Yr2,  "data.  The data range is determined by the years for which CHL was available. $V_{t-1}$ is CHL in the prior Jul-Jun season. Non-linearity is modeled as a 2nd-order polynomial due to data constraints and appears as $p()$ in the model equations.  The Oct-Mar catch is modeled as a function of Oct-Mar catch in the prior year only, without Jul-Sep catch 2-years prior as in the other covariate analyses.  This was done due to data constraints. The models are nested; the numeral indicates the level of nestedness. Models at levels 2 and higher are shown with the component that is added to the base level model (M) at top.")
fullcap=paste("Table ", ref(paste0(tabset,"nonspawner-model"), pre=pre), ". ", thecap, sep="")
kable(seltable, align="lcccccc", caption=fullcap, row.names=FALSE, escape=FALSE)
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

```{r table-appC-nonspawner-box3, echo=FALSE}
#set up table
seltable = data.frame(
  Model=paste("base model (M) ", Yr1,"-", Yr2, " data", sep=""), 
  Residual.df="", 
  MASE="",
  Adj.R2="", 
  F="", 
  p.value="", 
  AIC="", stringsAsFactors=FALSE)

m1 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE), data=dat.chl)
m2 = gam(nspawners0 ~ poly(nspawners1, 3, raw=TRUE), data=dat.chl)
a=anova(m1,m2, test="F")

#model 1
i=1; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="1. $ln(W_t) = \\alpha + p(ln(W_{t-1})) + \\epsilon_t$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F="", p.value="", 
  AIC=round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

## Add space
tmp1 = data.frame(Model="\\kern 1em", Residual.df="\\kern 1em", MASE="\\kern 1em", Adj.R2="\\kern 1em", F="\\kern 1em", p.value="\\kern 1em", AIC="")
seltable=rbind(seltable,tmp1)

for(covname in c("log.CHL.5.mon7to9.", "log.CHL.5.mon10to12.", "log.CHL.5.mon1to3.")){
#set up table
  if(covname=="log.CHL.5.mon1to3.")   covtit = "$V_t$ = Jan-Mar Chlorophyll"
  if(covname=="log.CHL.5.mon7to9.")   covtit = "$V_t$ = Jul-Sep Chlorophyll"
  if(covname=="log.CHL.5.mon10to12.") covtit = "$V_t$ = Oct-Dec Chlorophyll"


#set up the cov0 and cov1 variables
dat$cov0=dat[[paste(covname, "0", sep="")]]
dat$cov1=dat[[paste(covname, "1", sep="")]]
m1 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE), data=dat)
m2 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + cov0, data=dat)
m3 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(cov0, 2, raw=TRUE), data=dat)
m4 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(cov0, 2, raw=TRUE) + cov1, data=dat)
m5 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + poly(cov0, 2, raw=TRUE) + poly(cov1, 2, raw=TRUE), data=dat)
a=anova(m1,m2,m3,m4,m5, test="F")

#var header
seltable = rbind(seltable, data.frame(Model=covtit, Residual.df="", MASE="", Adj.R2="", F="", p.value="", AIC="", stringsAsFactors=FALSE))

#model 2
i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="2. $ln(W_t) = M + \\beta V_t$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#model 3
i=3; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="3. $ln(W_t) = M + p(V_t)$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

if(covname=="log.CHL.5.mon10to12."){
#model 4
i=4; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="4. $ln(W_t) = M + p(V_t) + \\beta V_{t-1}$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#model 5
i=5; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="5. $ln(W_t) = M + p(V_t) + p(V_{t-1})$", 
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)
}

m1 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE), data=dat)
m2 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + cov1, data=dat)
m3 = gam(nspawners0 ~ poly(nspawners1, 2, raw=TRUE) + s(cov1, sp=0.6), data=dat)
a=anova(m1,m2,m3, test="F")

#model 2
i=2; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="2. $ln(W_t) = M + \\beta V_{t-1}$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

#model 3
i=3; mod=paste("m",i,sep="")
aa = summary(get(mod))
tmp1=data.frame(
  Model="3. $ln(W_t) = M + p(V_{t-1})$",
  Residual.df=round(a[["Resid. Df"]][i],digits=1), 
  MASE=round(mean(abs(residuals(get(mod))))/NE,digits=3), 
  Adj.R2=100*round(aa$r.sq, digits=3), 
  F=round(a$F[i],digits=2), p.value = round(a[["Pr(>F)"]][i], digits=3), 
  AIC = round(AIC(get(mod)), digits=2))
seltable=rbind(seltable,tmp1)

## Add space
tmp1 = data.frame(Model="\\kern 1em", Residual.df="\\kern 1em", MASE="\\kern 1em", Adj.R2="\\kern 1em", F="\\kern 1em", p.value="\\kern 1em", AIC="")
seltable=rbind(seltable,tmp1)
}

# Remove space at top and bottom
seltable=seltable[1:(dim(seltable)[1]-1),]
```

```{r print-tableAppC-nonspawners-box5, echo=FALSE, eval=FALSE}
colnames(seltable)=c("Model", "Residual df", "MASE", "Adj.R2", "F", "p value", "AIC")
if(isLatex) colnames(seltable)=c("Model", "\\shortstack{Residual\\\\df}", "MASE", "\\shortstack{Adj.\\\\R2}", "F", "\\shortstack{p\\\\value}", "AIC")

thecap=paste("Model selection tests of Chlorophyll-a as an explanatory variable for the catch during the post-monsoon months (Oct-Mar) using box 5.")
fullcap=paste("Table ", ref(paste0(tabset,"nonspawner-model-box5"), pre=pre), ". ", thecap, sep="")
kable(seltable, align="lcccccc", caption=fullcap, row.names=FALSE, escape=FALSE)
```