---
title: "Raw Data"
output:
  pdf_document: default
  word_document: default
  header-includes: \usepackage[labelformat=empty]{caption}
---

<!-- 
header-includes: \usepackage[labelformat=empty]{caption}

Generic setup code common across all Rmds; run code in setup.Rmd if not knitting.
--> 

```{r child = file.path(here::here(), 'setup.Rmd')}
```

```{r echo=FALSE}
#set the table pre
Supplement=TRUE
if(Supplement){
  pre <- "S"
  tabset <- "tabsupp:"
}else{
  pre <- "H"
  tabset <- "tabappH:"
}
```

```{r child = file.path(here::here(), 'AppendixFiles','Appendix-Variables.Rmd')}
```

```{r getcovnames, echo=FALSE}
vars <- c(getnonspawnercovs()$allcovnames,
          getspawnercovs()$allcovnames)
vars <- unique(vars)
vars <- vars[str_sub(vars, str_length(vars))!=1]
```
```{r varnames}
varnames <- c(Year="Year",
              nspawners0="",
              spawners0="S",
              precip.gpcp.kerala.mon6to7.0 = "Jun-Jul Precip - ocean", 
              precip.gpcp.kerala.mon4to5.0 = "Apr-May Precip - ocean",
              Precip.Kerala.mon6to7.0 = "Jun-Jul Precip - land",
              Precip.Kerala.mon4to5.0 = "Apr-May Precip - land",
              SST.2.10.mon3to5.0 = "Apr-May r-SST",
              SST.2.5.mon10to12.0 = "Oct-Dec ns-SST",
              SST.UPW.4.mon6to9.0 = "Jun-Sep SST-UPW",
              SST.2.5.mon6to9.0 = "Jun-Sep ns-SST",
              SST.2.10.3.yr.runsum.0 = "2.5 yr ave r-SST",
              Bakun.UPW.mon6to9.0 = "Jun-Sep Bakun UPW",
              EMTPerp.UPW.mon6to9.0 = "Jun-Sep EMT - coast",
              Wetip.UPW.mon6to9.0 = "Jun-Sep Pumping - tip",
              ONI.mon7to6.0 = "ONI Jul-Jun",
              PDO.mon7to6.0 = "PDO Jul-Jun",
              AMO.mon7to6.0 = "AMO Jul-Jun",
              DMI.mon9to11.0 = "Sep-Nov DMI",
              SSTICOAD.2.10.3.yr.runsum.0 = "2.5 yr ave SST - ICOADS",
              log.CHL.2.5.mon7to9.0 = "Jul-Sep log ns-CHL",
              log.CHL.2.5.mon10to12.0 = "Oct-Dec log ns-CHL"
)
latexvarnames <- c(Year="Year",
              nspawners0="W",
              spawners0="S",
              precip.gpcp.kerala.mon6to7.0 = "\\shortstack{Jun-Jul\\\\o-Precip}", 
              precip.gpcp.kerala.mon4to5.0 = "\\shortstack{Apr-May\\\\o-Precip}",
              Precip.Kerala.mon6to7.0 = "\\shortstack{Jun-Jul\\\\l-Precip}",
              Precip.Kerala.mon4to5.0 = "\\shortstack{Apr-May\\\\l-Precip}",
              ONI.mon7to6.0 = "\\shortstack{Jul-Jun\\\\ONI}",
              PDO.mon7to6.0 = "\\shortstack{Jul-Jun\\\\PDO}",
              AMO.mon7to6.0 = "\\shortstack{Jul-Jun\\\\AMO}",
              DMI.mon9to11.0 = "\\shortstack{Sep-Nov\\\\DMI}",
              SSTICOAD.2.10.3.yr.runsum.0 = "\\shortstack{2.5 yr\\\\ave r-SST\\\\ICOADS}",
              SST.2.10.3.yr.runsum.0 = "\\shortstack{2.5 yr\\\\ave r-SST\\\\AVHRR}",
              Bakun.UPW.mon6to9.0 = "\\shortstack{Jun-Sep\\\\Bakun\\\\UPW}",
              EMTperp.UPW.mon6to9.0 = "\\shortstack{Jun-Sep\\\\coastal\\\\EMT}",
              Wetip.UPW.mon6to9.0 = "\\shortstack{Jun-Sep\\\\We\\\\tip}",
              SST.UPW.4.mon6to9.0 = "\\shortstack{Jun-Sep\\\\SST-diff\\\\UPW}",
              SST.2.10.mon3to5.0 = "\\shortstack{Apr-May\\\\r-SST}",
              SST.2.5.mon10to12.0 = "\\shortstack{Oct-Dec\\\\ns-SST}",
              SST.2.5.mon6to9.0 = "\\shortstack{Jun-Sep\\\\ns-SST}",
              log.CHL.2.5.mon7to9.0 = "\\shortstack{Jul-Sep\\\\log\\\\CHL}",
              log.CHL.2.5.mon10to12.0 = "\\shortstack{Oct-Dec\\\\log\\\\CHL}"
)
```

```{r table-appH-dat, echo=FALSE}
#dat.spawners defined in setup.Rmd
dat=fullrespdat
dat=subset(dat, Year<2016)
cols=c("Year", "nspawners0", "spawners0", vars,"log.CHL.2.5.mon7to9.0", "log.CHL.2.5.mon10to12.0")
if(!isLatex){
  dat <- dat[,names(varnames)]
  colnames(dat) <- varnames
}
```

```{r print-tableH-cols, echo=FALSE}
if(isLatex){
  dat <- dat[,names(latexvarnames)]
  colnames(dat) <- latexvarnames
}
```

```{r print-tableH-1, echo=FALSE}
cols1 <- names(dat)[c(1:7, 14:17)]
seltable = dat[,cols1]
n=ncol(seltable)
seltable[is.na(seltable)] <- NA

seltable[,2:n] <- round(seltable[,2:n], digits=2)
thecap=paste("Landings data and environmental covariates, part 1. W=Oct-Mar Kerala landings.  S=Jul-Sep Kerala landings. Values have been rounded to 2 digits. ns- = nearshore (0-80km) boxes 2 to 5 in Figure 1 (main text). r- = regional (0-160km) boxes 1 to 5 and 7 to 10. o-Precip is precipitation over the ocean; l-Precip is precipitation over land.")
fullcap=paste("Table ", ref(paste0(tabset, "data"), pre=pre), ". ", thecap, sep="")
al <- paste0("l", paste0(rep("c", n - 1), collapse=""))
if(isLatex){ 
  latexkable(seltable, fullcap, first.align="l")
  #kable(seltable, align=al, caption=fullcap, escape=FALSE, row.names=FALSE)
}else{
  library(kableExtra)
seltable %>%
  kbl(caption = fullcap, escape=FALSE, align=paste0("l", paste0(rep("c",dim(seltable)[2]-1),collapse=""))) %>%
  kable_classic(full_width = FALSE)
}
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

```{r print-tableH-2, echo=FALSE}
cols1 <- names(dat)[c(1, 18:20, 8:13)]
seltable = dat[,cols1]
seltable = seltable[!is.na(seltable[,2]),]
n=ncol(seltable)
seltable[is.na(seltable)] <- NA

seltable[,2:n] <- round(seltable[,2:n], digits=2)
thecap=paste("Landings data and environmental covariates, part 2.")
fullcap=paste("Table ", ref(paste0(tabset,"data-chl"), pre=pre), ". ", thecap, sep="")
al <- paste0("l", paste0(rep("c", n - 1), collapse=""))
if(isLatex){ 
  latexkable(seltable, fullcap, first.align="l")
  #kable(seltable, align=al, caption=fullcap, escape=FALSE, row.names=FALSE)
}else{
  library(kableExtra)
seltable %>%
  kbl(caption = fullcap, escape=FALSE, align=paste0("l", paste0(rep("c",dim(seltable)[2]-1),collapse=""))) %>%
  kable_classic(full_width = FALSE)
}
```

```{r, results="asis", echo=FALSE}
cat("\\clearpage")
```

```{r print-tableH-3, echo=FALSE}
cols1 <- colnames(dat)[c(1,21,22)]
seltable = dat[,cols1]
seltable = seltable[!is.na(seltable[,2]),]
n=ncol(seltable)
seltable[is.na(seltable)] <- NA

seltable[,2:n] <- round(seltable[,2:n], digits=2)
thecap=paste("Landings data and environmental covariates, part 3.")
fullcap=paste("Table ", ref(paste0(tabset,"data-chl"), pre=pre), ". ", thecap, sep="")
al <- paste0("l", paste0(rep("c", n - 1), collapse=""))
if(isLatex){ 
  latexkable(seltable, fullcap, first.align="l")
  #kable(seltable, align=al, caption=fullcap, escape=FALSE, row.names=FALSE)
}else{
  library(kableExtra)
seltable %>%
  kbl(caption = fullcap, escape=FALSE, align=paste0("l", paste0(rep("c",dim(seltable)[2]-1),collapse=""))) %>%
  kable_classic(full_width = FALSE)
}
```